### ISSUE TITLE
BigDecimal narrowing

### ISSUE THREAD

**Issue by skolson** [ionspin/kotlin-multiplatform-bignum#111]
It would be nice if BigDecimal implemented the (currently internal) interface in BigNumber of NarrowingOperations<BigDecimal> to support changing BigDecimals back to all the various basic types; Int, Long, Short, Float, Double, UInt, UShort, ULong, Byte and UByte,

Since BigDecimal is not "open"  extension functions are required to do this.  An example of one is below. 
```
/**
 * Returns a long value that truncates any digits to the right of the decimal.
 *
 * @param exactRequired if true and non-zero truncation error would result
 * @throws ArithmeticException if the value is to large or too small for a long, or if
 * exactRequired true and value to right of decimal is non-zero
 */
fun BigDecimal.longValue(exactRequired: Boolean = false): Long {
    val limit = BigDecimal.fromLong(Long.MAX_VALUE)
    val lowLimit = BigDecimal.fromLong(Long.MIN_VALUE)
    if (this > limit || this < lowLimit)
        throw ArithmeticException("Narrowing to Long would lose significant digits")
    return checkTruncation(exactRequired)
}

private fun BigDecimal.checkTruncation(exactRequired: Boolean):Long {
    val result = this.divideAndRemainder(BigDecimal.ONE)
    if (exactRequired && !result.second.isZero()) {
        throw ArithmeticException("Narrowing would lose precision")
    }
    val work = this.minus(result.first)
    return work.significand.longValue(exactRequired)
}
```
This would provide a superset of the narrowing operations provided in java's BigDecimal

**Comment by skolson** [comment]
Thanks for looking at this! Sorry that code above is just a sample and has a bug so don't use it :-)

**Comment by ionspin** [comment]
@skolson If you have time and would like to tackle this, a pull request would be great. I can help you out with any questions that you have regarding the internal organization of the library or possible ways to approach this.

**Comment by skolson** [comment]
I will try to work on this in a couple days. Will keep you posted here.

**Comment by skolson** [comment]
Ok, I have a first draft of code for this, but am having trouble with a couple unit tests. What environment do you use for debugging?  I'm using Android Studio but also have Intellij installed and could try there.  I see you have some JUnit tests in jvmTest but Android Studio doesn't seem to recognize the jvmTest/kotlin directory.  It looks like a sourceSet issue, as AS normally decorates sourceSet directories with green dots, and that isn't happening with jvmMain or jvmTest.
I can run unit tests fine in commonTest, which AS does decorate, but can't debug them with ADB. so am curious what your process is.
Also FYI I had to change dokka in the build.gradle scripts to 1.4.0-rc, which changed from "dokka" to "dokkaHtml" or "dokkaJavadoc".  I'm not a dokka user so I chose "dokkaJavadoc" just to get it to work.

**Comment by skolson** [comment]
Oops just noticing the gradle stuff that is linux-specific, so lemme see if I can get windows working for jvm target at least

**Comment by skolson** [comment]
Ok debugging fine now and have found a rounding issue. Lemme know if you want me to try to fix, or open another issue, or what.  Given this code:
```
val dub = BigDecimal.fromDouble(Double.MIN_VALUE)
val dub2 = dub.divide(BigDecimal.TEN)
```
Infinite precision should be in use, so this should get 4.9E-325 for dub2. Initially the correct new exponent of -325 is calculated, but then in fun roundDiscarded stuff gets lost, resulting in this debug output:
```
dub = {BigDecimal@1887} "4.9E-324"
 precision = 2
 significand = {BigInteger@2118} "49"
  magnitude = {long[1]@2120} 
   0 = 49
  numberOfWords = 1
  stringRepresentation = null
  sign = {Sign@1924} "POSITIVE"
 exponent = -324
 decimalMode = null
dub2 = {BigDecimal@2115} "0.E-318"
 precision = 0
 significand = {BigInteger@2121} "0"
  magnitude = {long[1]@2124} 
   0 = 0
  numberOfWords = 1
  stringRepresentation = null
  sign = {Sign@2125} "ZERO"
 exponent = -318
 decimalMode = {DecimalMode@1896} "DecimalMode(decimalPrecision=0, roundingMode=NONE)"
```

**Comment by ionspin** [comment]
Hey @skolson, if you want to tackle the rounding issue that would be great! I think it would be better to open a separate issue for that, and handle it in a separate pull request, as it's then easier to review. I'll try to adapt the build.gradle.kts to enable JVM on windows/mac/linux depending on a local gradle variable. I'll open a separate issue for that.

As far as the IDE goes, I would definitely recommend IntelliJ, I'm using Ultimate, but Community version should work fine as well. The reason is that AS is usually lagging a bit with bleeding edge kotlin support, although even when using IntelliJ you'll see some issues where gradle builds the project fine, but IntelliJ thinks there are errors (expected/actual implementation when using common native source set, and others)

**Comment by ionspin** [comment]
heres a pull request for windows development support, as well as fix for dokkaJavadoc https://github.com/ionspin/kotlin-multiplatform-bignum/pull/117

**Comment by skolson** [comment]
Thanks! I will get back to this on Tuesday, will keep you posted.

**Comment by ionspin** [comment]
I merged the gradle configuration changes to master, so now if you add `bignumPrimaryDevelopmentOs=windows` to your `gradle.properties` (should be in  C:\Users\<User>\. gradle\gradle.properties) build script will enable JVM and JS targets when you run `./gradlew build`

Same commit should also have fixed the dokkaJavadoc issue

**Comment by skolson** [comment]
Ok I'm gonna make a new issue and a different pull request for the rounding on division problem, and will work on that first as it'd be nice to have for the unit tests on the narrowing stuff.

**Comment by skolson** [comment]
I synced up the latest changes on the master, and now gradle is unhappy:
```
Host os name WINDOWS
[ios, ios32Arm, ios64Arm, macosX64, metadata, mingwX64, native, tvosArm64, tvosX64, watchosArm32, watchosArm64, watchosX86]
Dokka !
FAILURE: Build failed with an exception.
* What went wrong:
Task 'cleanJvmTest' not found in project ':bignum'.
```
I'm looking for the cause...

**Comment by skolson** [comment]
Well I have progress, but I keep hitting edge cases that trip up unit tests :-) This one is in BigInteger longValue implementation, which BigDecimal longValue relies on.  Doing this:
```
val l = BigInteger.fromLong(Long.MIN_VALUE)
val x = l.longValue()
```
x gets 0 instead of Long.MIN_VALUE, because the magnitude of Long.MIN_VALUE is actually 2 words. BigInteger longValue assumes correct value is in magnitude[0] which in this case is zero. (magnitude[1] = 1 in this case)
I think this is just because MIN_VALUE.abs is one larger than MAX_VALUE, so MIN_VALUE is the only value that can expose this error.  Any suggestions on a best fix for this one?
I'm close enough that it might be time for me to do the pull request so you can see what I have so far and we can decide what else needs doing (or undoing if I did something bad :-)). Unfortunately my pull request would have the fixes for both 111 and 114. I hope that's ok, I'm still a git newbie to these pull requests.

**Comment by ionspin** [comment]
Another great catch, the reason BigInteger needs two words to store Long.MIN_VALUE is because the current implementation uses 63 out of 64 bits to store the number data, the last bit I reserved for more efficient addition operations, as then there is no need to check for overflow. There is a check for this situation when converting from Long.MIN_VALUE, but not the other way around. I think I can fix that quickly and push to master.

As far as your pull request tackling two issues, that's completely fine!

Once again, thanks for all the effort you are putting into this!

**Comment by skolson** [comment]
Hey! I think I have another in BigInteger longValue, this one is on the exactRequired comparison.  This line I think is trouble:
```
if (exactRequired && (this > Long.MAX_VALUE.toUInt()))
```
because the UInt comes back with the max integer value, not the max long, so then the compare is done on the int....

**Comment by ionspin** [comment]
I'll fix that at the same time!

**Comment by ionspin** [comment]
Here is the pull request that should fix the conversion problem #120

**Comment by skolson** [comment]
Any near-term plans to do a 0.2.0 snapshot publish that would have these changes in it?

**Comment by ionspin** [comment]
Each merge to master is automatically published to sonatype snapshot, so the current 0.1.6-1.4.0-rc-SNAPSHOT has all the changes from this pull request (you can see the actual files here, note the timestamp at the end of the filename https://oss.sonatype.org/content/repositories/snapshots/com/ionspin/kotlin/bignum/0.1.6-1.4.0-rc-SNAPSHOT/). I'll bump the version up to 0.2.0 before the stable release, because there were enough changes to warrant it.

Btw, gradle can sometimes be uncooperative when the dependancies are already cached so you might need to do `./gradlew build --refresh-dependencies`

**Comment by skolson** [comment]
Ok cool, I saw the target on the issue being 0.2.0 and thought it was waiting for that.

**Comment by skolson** [comment]
Hmm, I did the --refresh-dependencies, and the jar gradle has was built last night.  So is the sources jar. But AS is still not able to resolve the new code, and if I look in the sources jar, the new code isn't in that source either. So it's like the new stuff isn't merged or something?

**Comment by ionspin** [comment]
It''s already there end of each build on master branch directly publishes to sonatype repository. I just tested it in a separate project and I'm seeing new narrowing functions. 
If you are not seeing it it might be that Gradle is still using cached libraries (which hopefully --refresh-dependencies solves), or that Android Stuido is using cached libraries. In Android studio you can open Gradle tab, for me it's on the right side, right click on the project name and select `Refresh Gradle Dependencies`

But as I said it's finicky, i had several occasions where I had to delete gradle and m2 cache folders and reimport AS/IntelliJ project before the changes were visible, although it did get much better lately.
